services:
  - type: web
    name: csa-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host=0.0.0.0 --port=$PORT"
    plan: free
    autoDeploy: true
    region: vietnam
