"""add debt_amount to bookings

Revision ID: 38463eb4cda4
Revises: 5cd02e31a28a
Create Date: 2025-07-06 10:29:14.465438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38463eb4cda4'
down_revision: Union[str, Sequence[str], None] = '5cd02e31a28a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'booking_services', 'services', ['service_id'], ['id'])
    op.add_column('bookings', sa.Column('debt_amount', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'debt_amount')
    op.drop_constraint(None, 'booking_services', type_='foreignkey')
    # ### end Alembic commands ###
