"""Add debt_note to bookings

Revision ID: 51d4b64e8f29
Revises: b53184e2ad5a
Create Date: 2025-07-01 11:32:04.116374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d4b64e8f29'
down_revision: Union[str, Sequence[str], None] = 'b53184e2ad5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('debt_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'debt_note')
    # ### end Alembic commands ###
