"""Add amount_paid

Revision ID: 5cd02e31a28a
Revises: 51d4b64e8f29
Create Date: 2025-07-01 17:01:00.970869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd02e31a28a'
down_revision: Union[str, Sequence[str], None] = '51d4b64e8f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('amount_paid', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'amount_paid')
    # ### end Alembic commands ###
