"""init booking and member tables

Revision ID: 768b4379681a
Revises: 
Create Date: 2025-06-25 23:28:29.049142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '768b4379681a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.add_column('bookings', sa.Column('grand_total', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('log_history', sa.Text(), nullable=True))
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_column('bookings', 'log_history')
    op.drop_column('bookings', 'payment_method')
    op.drop_column('bookings', 'discount')
    op.drop_column('bookings', 'grand_total')
    op.create_table('services',
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('services_pkey'))
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    # ### end Alembic commands ###
